### ISSUE TITLE
Detailed setup guideline instead of Docker

### ISSUE THREAD

**Issue by Hyeokreal** [Bibyutatsu/TorchRT#1]
Hi Bibyutatsu,

Thank you for sharing your great work!

I'm wondering how can I setup the environment in detail but it's hard to figure out since it is wrapped with docker.
Could you share the guideline of environment setup instead of Docker ?

**Comment by Bibyutatsu** [comment]
Hi @Hyeokreal ,
Yeah sure I will share the guidelines in the Readme. 

For setting up your environment I think you can follow the detailed steps they mentioned [here]( https://github.com/NVIDIA/TensorRT)

I am closing this issue. If you have any other difficulty you can ask here.
